language: php

php:
  - 7.4
  - 8.0
  - 8.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - composer install -n --dev --prefer-source

script: vendor/bin/phpunit
